# Generated by Django 4.1.2 on 2022-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_experience_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='experience_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
