# Generated by Django 4.1.2 on 2022-10-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_experience_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='experience_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
