# Generated by Django 4.1.2 on 2022-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_experience_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='experience_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='experience_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
